name: Document

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        - toolchain: nightly
    - name: Build Documentation
      run: cargo +nightly doc --no-deps
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/doc
